######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 26 23:16:40 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += appMain.cpp
QT += network
